export const Data = [
  {
    type: "web",
    id: "sontag",
    title: "The Sontag Foundation",
    subtitle: "The definitive enterprise for brain cancer research.",
    year: "2021",
    tags: ["WordPress", "JavaScript", "Styled Components"],
    agency: "Push10",
    url: "sontagfoundation.org",
    link: "https://sontagfoundation.org",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras malesuada felis sit amet ligula maximus, nec blandi test porta. Fusce euismod accumsan lacus, non tempus null. Nec blandi test porta. Fusce euismod accumsan lacus, non tempus null.",
  },
  {
    type: "web",
    id: "hhmi",
    title: "Howard Hughes' Biointeractive",
    subtitle: "Netflixing science, for kids.",
    year: "2020",
    tags: ["Drupal 8", "JavaScript", "Styled Components"],
    agency: "ForumOne",
    url: "biointeractive.org",
    link: "https://biointeractive.org",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras malesuada felis sit amet ligula maximus, nec blandi test porta. Fusce euismod accumsan lacus, non tempus null. Nec blandi test porta. Fusce euismod accumsan lacus, non tempus null.",
  },
  {
    type: "web",
    id: "vilcek",
    title: "Vilcek Foundation",
    subtitle: "A celebration of immigrants & the art.",
    year: "2020",
    tags: ["WordPress", "JavaScript", "Styled Components"],
    agency: "ForumOne",
    url: "vilcek.org",
    link: "https://vilcek.org",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras malesuada felis sit amet ligula maximus, nec blandi test porta. Fusce euismod accumsan lacus, non tempus null. Nec blandi test porta. Fusce euismod accumsan lacus, non tempus null.",
  },
  {
    type: "web",
    id: "exhaustnotes",
    title: "Exhaust Notes",
    subtitle: "Car revs on demand.",
    year: "2019",
    tags: ["React", "Custom SASS/CSS"],
    agency: "Passion Project",
    url: "exhaustnotes.co",
    link: "https://exhaustnotes.co",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras malesuada felis sit amet ligula maximus, nec blandi test porta. Fusce euismod accumsan lacus, non tempus null. Nec blandi test porta. Fusce euismod accumsan lacus, non tempus null.",
  },
  {
    type: "web",
    id: "amanda",
    title: "The Amanda Foundation",
    subtitle: "A mission-driven adoption center.",
    year: "2020",
    tags: ["Squarespace", "JavaScript", "Custom HTML+CSS"],
    agency: "ForumOne",
    url: "amandafoundation.org",
    link: "https://amandafoundation.org",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Cras malesuada felis sit amet ligula maximus, nec blandi test porta. Fusce euismod accumsan lacus, non tempus null. Nec blandi test porta. Fusce euismod accumsan lacus, non tempus null.",
  },
  {
    type: "photography",
    id: "portraits",
    title: "Portraits",
    subtitle: "Brain Cancer",
    photos: "",
  },
  {
    type: "photography",
    id: "cosplay",
    title: "Cosplay",
    subtitle: "Brain Cancer",
    photos: "",
  },
  {
    type: "photography",
    id: "nature",
    title: "Nature",
    subtitle: "Brain Cancer",
    photos: "",
  },
];
